version: "3.7"
services:

  seedbox:
   container_name: deluge
   image: lscr.io/linuxserver/deluge
   restart: unless-stopped
   network_mode: service:vpn-sidecar
   depends_on:
     - vpn-sidecar
   volumes:
     - deluge-data-volume:/config
     - downloads-volume:/torrents

  web-proxy:
    container_name: proxy
    image: dperson/nginx
    restart: unless-stopped
    environment:
      - PROXY=http://seedbox:8112;/
    ports:
      - 8112:80/tcp
    links:
      - vpn-sidecar:seedbox
    depends_on:
      - seedbox
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    networks:
      - default
      - isolated_torrent_network

  vpn-sidecar:
    restart: unless-stopped
    networks:
      - isolated_torrent_network

    # use this block for OpenVPN
    container_name: ovpnclient
    image: dperson/openvpn-client
    cap_add:
      - NET_ADMIN
    read_only: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - openvpn-client-config-volume:/vpn
    environment:
      FIREWALL: ""
      # VPNPORT: "42069;udp" # port forwarding for seedbox
      # VPNPORT_2: "42069;tcp"
      # VPNPORT_3: "4001;udp"
      # VPNPORT_4: "4001;tcp"
      OTHER_ARGS: "--mute-replay-warnings" # optional
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 # for raspberry pi compatibility?
      
    # use this block for Wireguard
    # container_name: wgclient
    # image: lscr.io/linuxserver/wireguard
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_MODULE
    # volumes:
    #   - /lib/modules:/lib/modules
    #   - wgclient-data-volume:/config
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1
    #   - net.ipv6.conf.all.disable_ipv6=0 # for raspberry pi compatibility?

volumes:
  deluge-data-volume: # deluge application files - change to a persistent location
    driver_opts:
        type: tmpfs
        device: tmpfs
  downloads-volume: # (optional) torrent download location - change to a persistent location
    driver_opts:
        type: tmpfs
        device: tmpfs
  openvpn-client-config-volume: # read-only location of *.ovpn
    driver: local
    driver_opts:
        o: bind
        type: none
        device: "$PWD/openvpn/"   
  # wgclient-data-volume: # writeable location of wg0.conf
  #   driver: local
  #   driver_opts:
  #       o: bind
  #       type: none
  #       device: "$PWD/wireguard/"

networks:
  default:
  isolated_torrent_network:
